Add a final step to report test failures properly

diff --git a/.github/workflows/ci-mac.yml b/.github/workflows/ci-mac.yml
--- a/.github/workflows/ci-mac.yml
+++ b/.github/workflows/ci-mac.yml
@@ -173,6 +173,7 @@ jobs:
           fi
 
       - name: Run Tests
+        id: run_tests
         continue-on-error: true
         timeout-minutes: 10
         run: |
@@ -210,3 +211,9 @@ jobs:
           TIMESTAMP=$(date +%Y_%m_%d)
           aws s3 cp ${{ env.DIST_DIR }}/${{ env.BUILD_FILE_NAME }}.app.zip s3://${{ secrets.AWS_S3_BUCKET }}/test/$TIMESTAMP/mac/${{ matrix.os-version }}/ \
             --no-progress
+      
+      - name: Announce Test Failure
+        if: steps.run_tests.outcome == 'failure'
+        run: |
+          echo "Tests have failed!"
+          exit 1
diff --git a/.github/workflows/ci-windows.yml b/.github/workflows/ci-windows.yml
--- a/.github/workflows/ci-windows.yml
+++ b/.github/workflows/ci-windows.yml
@@ -109,6 +109,9 @@ jobs:
           }
 
       - name: Run Tests
+        id: run_tests
+        continue-on-error: true
+        timeout-minutes: 10
         run: |
           cd ${{ env.BUILD_DIR }}/${{ inputs.cmake_config_preset }}
           ctest `
@@ -145,3 +148,9 @@ jobs:
           $timestamp = Get-Date -Format "yyyy_MM_dd"
           aws s3 cp --recursive ${{ env.DIST_DIR }} s3://${{ secrets.AWS_S3_BUCKET }}/test/$timeStamp/windows/ `
             --no-progress
+      
+      - name: Announce Test Failure
+        if: steps.run_tests.outcome == 'failure'
+        run: |
+          echo "Tests have failed!"
+          exit 1
