Add macOS Nightly and S3 Workflow (#816)
* Add initial ci-mac.yml workflow

* Update s3 command to use timestamp and recursive

* Add CTest step to ci-mac.yml

* Add lfs to checkout step

* Add enable_full_os_versions input to ci-controller.yml

* Update job name for ci-mac.yml

* Add OIDC permissions to ci-mac.yml

* Update logic in setup-os-versions step

* Change distribution artifact to zip for macOS

* Rework artifact logic in ci-mac.yml

* Add CTest timeout at 10 mins, continue-on-error to test step

* Add a final step to report test failures properly

* Fix issue with workflow_dispatch inputs in ci-controller.yml

* Minor edit to setup-os-versions step

* Fix line at end of file

diff --git a/.github/workflows/ci-ubuntu.yml b/.github/workflows/ci-ubuntu.yml
--- a/.github/workflows/ci-ubuntu.yml
+++ b/.github/workflows/ci-ubuntu.yml
@@ -95,6 +95,9 @@ jobs:
           fi
 
       - name: Run Tests
+        id: run_tests
+        continue-on-error: true
+        timeout-minutes: 10
         run: |
           cd ${{ env.BUILD_DIR }}
           ctest \
@@ -132,3 +135,9 @@ jobs:
           TIMESTAMP=$(date +%Y_%m_%d)
           aws s3 cp --recursive ${{ env.DIST_DIR }} s3://${{ secrets.AWS_S3_BUCKET }}/test/$TIMESTAMP/ubuntu/${{ matrix.os-version }}/ \
             --no-progress
+
+      - name: Announce Test Failure
+        if: steps.run_tests.outcome == 'failure'
+        run: |
+          echo "Tests have failed!"
+          exit 1
